### PR TITLE
Update to RC2

### PR DESCRIPTION
**Pull request by AlekseyMartynov**

### CODE REVIEW

**Comment by IlyaKhD** [comment]
:+1:

**Comment by AlekseyMartynov** [comment]
Hey @IlyaKhD how are you doing?

**Comment by IlyaKhD** [comment]
Fine and you?
Glad to see RC2 is coming. Woho! Enums got tooling support finaly :smile:

**Comment by AlekseyMartynov** [comment]
> Enums got tooling support finaly

And this exposes [places](https://github.com/AlekseyMartynov/DevExtreme.AspNet.TagHelpers/blob/f9afce2d950b2fd7f92b8a46118d3b5eea7e5cf7/Samples/Views/Widgets/PieChart.cshtml#L18) where we have to use `Object` type :smile:

**Comment by IlyaKhD** [comment]
For some reason we can't make an omelet without breaking eggs (-:

**Pull request merged**
