### PR TITLE
Clean command added to the Generator

### PR DESCRIPTION
**Pull request by IlyaKhD**

### CODE REVIEW

**Comment by AlekseyMartynov** [comment]
Hi @IlyaKhD 
Nice command!
Would you provide some usage scenarios?

**Comment by IlyaKhD** [comment]
This little feature is just a 'work-flow sugar' and might sometimes be useful.

I.E. while modifying the Generator code generated files can be added under source control to track the changes (since we do not have any generator output tests). After that these files are to be removed.

**Comment by AlekseyMartynov** [comment]
How about `del /s *.g.cs` :smile:

**Comment by IlyaKhD** [comment]
Do you really think it is more convenient to navigate to the the solution root and type `del /s *.g.cs` then just `dnx clean` in the Generator dir?

Our Generator is a self-sufficient console app that is able both to ***generate Files*** and ***delete generated files***. Why should one use `del /s *.g.cs` if the Generator is already responsible for deleting generated files and can provide this command?

Moreover - what if someone downloads the sources just to play around and wants to see how the Generator works? We have to explain that all the generated files are placed here and have a **.g.cs** extension. :smile:

**Comment by AlekseyMartynov** [comment]
@IlyaKhD
Wait a minute. To my understanding, there's currently no need to delete generated files. You claim it's sometimes useful during development. I won't argue what's more convenient, but in both instances one optionally changes the working directory and types a command, `del /s *.g.cs` or `dnx clean-only`. Honestly I'd prefer the `del` way :smile: 

Regarding the need to explain, good point! I think we could add some kind of a document describing how the Generator works.

**Comment by IlyaKhD** [comment]
My story is like this: I had a need to delete generated files and my first intention was to check if the Generator has such a command.
So, from my point this functionality could be added to the Generator because it's the first place coming to mind if someone encounters "*delete generated files*" task.

Anyway, this is a minor issue and it does not deserve so much disputing on it. 
As we can see, several options are available and different people choose different ways so let's choose the most chip one - change nothing :smile: .

**Comment by IlyaKhD** [comment]
Btw, @AlekseyMartynov  would you file an issue for creating the document describing how the Generator works?

**Comment by AlekseyMartynov** [comment]
Added to Trello

**Pull request closed without merging**
